Merolekiando/Models/Province.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Merolekiando.Models
{
    public partial class Province
    {
        public Province()
        {
            Municipalities = new HashSet<Municipality>();
            ProdProvinces = new HashSet<ProdProvince>();
            Users = new HashSet<User>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int? Time { get; set; }

        public virtual ICollection<Municipality> Municipalities { get; set; }
        public virtual ICollection<ProdProvince> ProdProvinces { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}

Merolekiando/Controllers/ProvinceController.cs
using Merolekiando.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Merolekiando.Controllers
{
    public class ProvinceController : Controller
    {
        private readonly MerolikandoDBContext _Context;
        public ProvinceController(MerolikandoDBContext Context)
        {
            _Context = Context;
        }
        public IActionResult Index()
        {
            var UsId = HttpContext.Session.GetInt32("userId");
            if (UsId != null)
            {
                ViewBag.Provices = _Context.Provinces.ToList();
                return View();
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult Municiplity(int Id)
        {
            var UsId = HttpContext.Session.GetInt32("userId");
            if (UsId != null)
            {
                ViewBag.Municipilities = _Context.Municipalities.Where(a => a.PrvId == Id).ToList();
                ViewBag.ProvinceName = _Context.Provinces.Where(a => a.Id == Id).Select(a => a.Name).FirstOrDefault();
                ViewBag.PrvId = Id;
                return View();
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult Manage(Province dt)
        {
            var UsId = HttpContext.Session.GetInt32("userId");
            if (UsId != null)
            {
                try
                {
                    if (dt.Id > 0)
                    {
                        var data = _Context.Provinces.Where(a => a.Id == dt.Id).FirstOrDefault();
                        data.Name = dt.Name;
                        _Context.Provinces.Update(data);
                        _Context.SaveChanges();
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        Province province = new();
                        province.Name = dt.Name;
                        province.Time = (int)DateTimeOffset.Now.ToUnixTimeMilliseconds();
                        _Context.Provinces.Add(province);
                        _Context.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }
                catch (System.Exception)
                {
                    throw;
                }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult ManageMunicipality(Municipality dt)
        {
            var UsId = HttpContext.Session.GetInt32("userId");
            if (UsId != null)
            {
                try
            {
                if (dt.Id > 0)
                {
                    var data = _Context.Municipalities.Where(a => a.Id == dt.Id).FirstOrDefault();
                    data.Name = dt.Name;
                    _Context.Municipalities.Update(data);
                    _Context.SaveChanges();
                    return RedirectToAction("Municiplity", new { id = dt.PrvId });
                }
                else
                {
                    Municipality province = new();
                    province.Name = dt.Name;
                    province.Time = (int)DateTimeOffset.Now.ToUnixTimeMilliseconds();
                    province.PrvId = dt.PrvId;
                    _Context.Municipalities.Add(province);
                    _Context.SaveChanges();
                    return RedirectToAction("Municiplity", new { id = dt.PrvId });
                }
            }
            catch (Exception)
            {

                throw;
            }
            }
            return RedirectToAction("Login", "Home");
        }
        public IActionResult ProvinceEditModal(int id)
        {
            var dto = _Context.Provinces.Where(a => a.Id == id).FirstOrDefault();
            return PartialView("~/Views/Province/_ProvinceEditModal.cshtml", dto);
        }
        public IActionResult ProvinceDeleteModal(int id)
        {
            var dto = _Context.Provinces.Where(a => a.Id == id).FirstOrDefault();
            return PartialView("~/Views/Province/_ProvinceDeleteModal.cshtml", dto);
        }
        public IActionResult MunicipalityEditModal(int id)
        {
            var dto = _Context.Municipalities.Where(a => a.Id == id).FirstOrDefault();
            return PartialView("~/Views/Province/_MunicipalityEditModal.cshtml", dto);
        }
        public IActionResult MunicipalityDeleteModal(int id)
        {
            var dto = _Context.Municipalities.Where(a => a.Id == id).FirstOrDefault();
            return PartialView("~/Views/Province/_MunicipalityDeleteModal.cshtml", dto);
        }
        public async Task<IActionResult> DeleteProvinces(int id)
        {
            var UsId = HttpContext.Session.GetInt32("userId");
            if (UsId != null)
            {
                try
                {
                    var prdPrvnc = await _Context.ProdProvinces.Where(a => a.ProvinceId == id).ToListAsync();
                    _Context.ProdProvinces.RemoveRange(prdPrvnc);
                    _Context.SaveChanges();

                    var mncLst = await _Context.Municipalities.Where(a => a.PrvId == id).ToListAsync();
                    foreach (var item in mncLst)
                    {
                        var prodMnc = await _Context.ProdMunicipalities.Where(a => a.MncId == item.Id).ToListAsync();
                        _Context.ProdMunicipalities.RemoveRange(prodMnc);
                        _Context.SaveChanges();

                        var users = await _Context.Users.Where(a => a.MunicipalityId == item.Id).ToListAsync();

                        foreach (var itm in users)
                        {
                            itm.Municipality = null;
                            _Context.Users.Update(itm);
                            _Context.SaveChanges();
                        }
                    }

                    var usr = await _Context.Users.Where(a => a.ProvinceId == id).ToListAsync();
                    foreach (var item in usr)
                    {
                        item.ProvinceId = null;
                        _Context.Users.Update(item);
                        _Context.SaveChanges();
                    }
                    var prvnce = _Context.Provinces.Where(a => a.Id == id).FirstOrDefault();
                    if (prvnce != null)
                    {
                        _Context.Provinces.Remove(prvnce);
                        _Context.SaveChanges();
                    }
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    throw;
                }

            }
            return RedirectToAction("Login", "Home");
        }
        public async Task<IActionResult> DeleteMunicipality(int id)
        {
            var UsId = HttpContext.Session.GetInt32("userId");
            if (UsId != null)
            {
                try
                {
                    var prodMnc = await _Context.ProdMunicipalities.Where(a => a.MncId == id).ToListAsync();
                    _Context.ProdMunicipalities.RemoveRange(prodMnc);
                    _Context.SaveChanges();

                    var users = await _Context.Users.Where(a => a.MunicipalityId == id).ToListAsync();
                    foreach (var user in users)
                    {
                        user.MunicipalityId = null;
                        _Context.Users.Update(user);
                        _Context.SaveChanges();
                    }

                    var mnc = _Context.Municipalities.Where(a => a.Id == id).FirstOrDefault();
                    _Context.Municipalities.Remove(mnc);
                    _Context.SaveChanges();

                    return RedirectToAction("Municiplity", new {id = mnc.PrvId });
                }
                catch (Exception)
                {

                    throw;
                }
            
            }
            return RedirectToAction("Login", "Home");
        }
    }
}

Merolekiando/Views/Province/Index.cshtml
<div class="container-fluid plr_30 body_white_bg pt_30">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="QA_section">
                <div class="white_box_tittle list_header">
                    <h4>Provinces</h4>
                    <div class="box_right d-flex lms_block">
                        <div class="add_button ms-2">
                            <a href="#" data-bs-toggle="modal" data-bs-target="#AddCateModal" class="btn_1">Add New</a>
                        </div>
                    </div>
                </div>
                <div class="QA_table">

                    <table class="table lms_table_active">

                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in @ViewBag.Provices)
                            {
                                <tr>
                                    <th scope="row"> <a asp-controller="Province" asp-action="Municiplity" asp-route-id="@item.Id" class="question_content"> @item.Name</a></th>
                                    <td>
                                        <a href="#" data-target="@item.Id" id="EditClick" class="status_btn">Edit</a>
                                        <a href="#" data-target="@item.Id" id="DeleteClick" style="background-color:red;" class="status_btn">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-bs-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Provice</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="FileForm" action="~/Province/Manage" method="post">
                <div class="modal-body">
                    <div class="white_card_body" id="CatId">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>


<div class="modal fade" id="exampleModalDelete" tabindex="-1" role="dialog" aria-bs-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Provice</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="FileForm" action="~/Province/DeleteProvinces" method="post">
                <div class="modal-body">
                    <div class="white_card_body">
                        <h4> Are you sure to delete this record? </h4>
                    </div>
                    <div class="white_card_body" id="DelCatId">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-primary">Yes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="AddCateModal" tabindex="-1" role="dialog" aria-bs-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Province</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="FileForm" action="~/Province/Manage" method="post">
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label" for="exampleFormControlInput1">Name</label>
                        <input type="text" name="Name" class="form-control" value="" placeholder="">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    $(document).on('click', 'tr td a#EditClick', function () {
    //$("#PosClick").click(function () {
            debugger
        var val = $(this).attr("data-target");
            $.ajax({
                type: 'post',
                url: '@Url.Action("ProvinceEditModal", "Province")',
                data: { 'id': val },
                contenttype: 'application/json; charset=utf-8',
                async: true,
                success: function (data) {
                    debugger
                    $('#exampleModal').modal('show');
                    $("#CatId").html(data);
                },
                error: function (xhr) {
                    alert('error');
                }
        })

    });
    $(document).on('click', 'tr td a#DeleteClick', function () {
    //$("#PosClick").click(function () {
            debugger
        var val = $(this).attr("data-target");
            $.ajax({
                type: 'post',
                url: '@Url.Action("ProvinceDeleteModal", "Province")',
                data: { 'id': val },
                contenttype: 'application/json; charset=utf-8',
                async: true,
                success: function (data) {
                    debugger
                    $('#exampleModalDelete').modal('show');
                    $("#DelCatId").html(data);
                },
                error: function (xhr) {
                    alert('error');
                }
        })

    });
</script>

Merolekiando/Views/Province/Municiplity.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid plr_30 body_white_bg pt_30">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="QA_section">
                <div class="white_box_tittle list_header">
                    <h4>Municipalities by @ViewBag.ProvinceName</h4>
                    <div class="box_right d-flex lms_block">
                        <div class="add_button ms-2">
                            <a href="#" data-bs-toggle="modal" data-bs-target="#AddMunicModal" class="btn_1">Add New</a>
                        </div>
                    </div>
                </div>
                <div class="QA_table">

                    <table class="table lms_table_active">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in @ViewBag.Municipilities)
                            {
                                <tr>
                                    <th scope="row"> <a href="#" class="question_content"> @item.Name</a></th>
                                    <td>
                                        <a href="#" data-target="@item.Id" id="EditClick" class="status_btn">Edit</a>
                                        <a href="#" data-target="@item.Id" id="DeleteClick" style="background-color:red" class="status_btn">Delete</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-bs-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Municipality</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="FileForm" action="~/Province/ManageMunicipality" method="post">
                <div class="modal-body">
                    <div class="white_card_body" id="CatId">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="exampleDeleteModal" tabindex="-1" role="dialog" aria-bs-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete Municipality</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="FileForm" action="~/Province/DeleteMunicipality" method="post">
                <div class="modal-body">
                    <div class="white_card_body">
                        <h4> Are you sure to delete this record? </h4>
                    </div>
                    <div class="white_card_body" id="DelCatId">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                    <button type="submit" class="btn btn-primary">Yes</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="modal fade" id="AddMunicModal" tabindex="-1" role="dialog" aria-bs-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Category</h5>
                <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="FileForm" action="~/Province/ManageMunicipality" method="post">
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label" for="exampleFormControlInput1">Name</label>
                        <input type="text" name="Name" class="form-control" value="" placeholder="">
                        <input type="text" name="PrvId" hidden class="form-control" value="@ViewBag.PrvId" placeholder="">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script>

    $(document).on('click', 'tr td a#EditClick', function () {
    //$("#PosClick").click(function () {
            debugger
        var val = $(this).attr("data-target");
            $.ajax({
                type: 'post',
                url: '@Url.Action("MunicipalityEditModal", "Province")',
                data: { 'id': val },
                contenttype: 'application/json; charset=utf-8',
                async: true,
                success: function (data) {
                    debugger
                    $('#exampleModal').modal('show');
                    $("#CatId").html(data);
                },
                error: function (xhr) {
                    alert('error');
                }
        })

    });

    $(document).on('click', 'tr td a#DeleteClick', function () {
    //$("#PosClick").click(function () {
            debugger
        var val = $(this).attr("data-target");
            $.ajax({
                type: 'post',
                url: '@Url.Action("MunicipalityDeleteModal", "Province")',
                data: { 'id': val },
                contenttype: 'application/json; charset=utf-8',
                async: true,
                success: function (data) {
                    debugger
                    $('#exampleDeleteModal').modal('show');
                    $("#DelCatId").html(data);
                },
                error: function (xhr) {
                    alert('error');
                }
        })

    });
</script>

Merolekiando/Views/Province/_MunicipalityDeleteModal.cshtml
@model Merolekiando.Models.Municipality

<div class="mb-3">
    <input type="text" name="id" hidden class="form-control" value="@Model.Id" placeholder="">
</div>

Merolekiando/Views/Province/_MunicipalityEditModal.cshtml
@model Merolekiando.Models.Municipality

<div class="mb-3">
    <label class="form-label" for="exampleFormControlInput1">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" placeholder="">
    <input type="text" name="Id" class="form-control" value="@Model.Id" id="CateId" hidden>
    <input type="text" name="PrvId" hidden class="form-control" value="@Model.PrvId" placeholder="">
</div>

Merolekiando/Views/Province/_ProvinceDeleteModal.cshtml
@model Merolekiando.Models.Province

<div class="mb-3">
    <input type="text" name="Id" class="form-control" value="@Model.Id" id="CateId" hidden>
</div>

Merolekiando/Views/Province/_ProvinceEditModal.cshtml
@model Merolekiando.Models.Province

<div class="mb-3">
    <label class="form-label" for="exampleFormControlInput1">Name</label>
    <input type="text" name="Name" class="form-control" value="@Model.Name" placeholder="">
    <input type="text" name="Id" class="form-control" value="@Model.Id" id="CateId" hidden>
</div>